#!/usr/bin/expect -f

set action [lindex $argv 0];
set device "32:08:D5:42:A3:38"
set timeout 10

spawn bluetoothctl
expect "Agent registered"
send -- "power on\r"
send -- "remove $device\r"
expect {
	"Device $device not available" { 
		send -- "scan on\r"
		expect "$device"
		send -- "connect $device\r"
		expect "Connection successful"
		send -- "scan off\r"
	}
	"Device has been removed" { send -- "remove $device\r" }
}
send -- "exit\r"
expect eof
